# Generated by Django 5.2.6 on 2025-10-30 13:00

import HelloWorld.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_email', models.CharField(max_length=100)),
                ('stu_total_attendances', models.IntegerField(default=0)),
                ('stu_enroll_MU098', models.BooleanField(default=False)),
                ('stu_enroll_MU099', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(default=HelloWorld.models.next_id, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('event_location', models.CharField(blank=True, max_length=100, null=True)),
                ('mu_required', models.BooleanField(default=False)),
                ('attendees', models.ManyToManyField(to='HelloWorld.student')),
            ],
        ),
    ]
