# Generated by Django 5.2.6 on 2025-12-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloWorld', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.AddField(
            model_name='student',
            name='attended_events',
            field=models.ManyToManyField(to='HelloWorld.event'),
        ),
    ]
