# Generated by Django 5.2.6 on 2025-10-29 02:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('eventId', models.CharField(max_length=255)),
                ('name', models.CharField(help_text='Event Title/Summary', max_length=255)),
                ('status', models.CharField(default='pending', help_text='Calendar event Status', max_length=50)),
                ('htmlLink', models.URLField(blank=True, help_text='Public Calendar link', null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Event Creation Date')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, help_text='Event Updated Date')),
                ('summary', models.CharField(help_text='Event Description', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Event Location', max_length=255, null=True)),
                ('creator_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organizerEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('organizerName', models.CharField(blank=True, max_length=255, null=True)),
                ('StartTime', models.TimeField(help_text='Event Start Time', verbose_name='Start Time')),
                ('startDate', models.DateField(help_text='Event start date')),
                ('endDate', models.DateField(help_text='Event end date')),
                ('roll', models.BooleanField(default=False, help_text='??????')),
                ('url_text', models.CharField(blank=True, max_length=255, null=True)),
                ('short_title', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, help_text='Optional image for this event', null=True, upload_to='mystaticfiles/')),
                ('pamphlet', models.TextField(blank=True, null=True, verbose_name='Program')),
            ],
        ),
    ]
