# Generated by Django 5.2.6 on 2025-09-27 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('room', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('what_three_words', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start_time', models.DateTimeField()),
                ('date_end_time', models.DateTimeField()),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brunneus_ferrum_malleus.location')),
            ],
        ),
    ]
