# Generated by Django 5.2.6 on 2025-10-28 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brunneus_ferrum_malleus', '0002_alter_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('present', models.BooleanField(default=True)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brunneus_ferrum_malleus.event')),
            ],
            options={
                'unique_together': {('event', 'email')},
            },
        ),
    ]
