# Generated by Django 4.2.6 on 2024-02-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(help_text='Has this order been delivered to the customer?', verbose_name='Has been completed')),
                ('customer_name', models.CharField(max_length=255)),
                ('scoops', models.ManyToManyField(to='icecream.flavor')),
            ],
        ),
    ]
