# Generated by Django 4.2.4 on 2024-02-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(help_text='Has this order been delivered to the customer?', verbose_name='Was delivered'),
        ),
    ]
