# Generated by Django 5.0.2 on 2024-02-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0002_alter_order_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Has this order been delivered to the customer?', verbose_name='Was delivered'),
        ),
    ]
