# Generated by Django 5.0.2 on 2026-02-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0003_alter_order_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=1023, verbose_name='Description')),
            ],
        ),
    ]
