# Generated by Django 5.2.6 on 2025-09-23 22:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet', '0002_alter_event_institution_elements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elements',
            new_name='Element',
        ),
    ]
