# Generated by Django 5.2.6 on 2025-09-23 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet', '0003_rename_elements_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='event',
        ),
        migrations.CreateModel(
            name='EventSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaflet.event')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='event_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leaflet.eventsection'),
        ),
    ]
