# Generated by Django 5.2.6 on 2025-09-24 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet', '0004_remove_element_event_eventsection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='element_title',
        ),
    ]
