# Generated by Django 5.2.6 on 2025-10-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet', '0005_remove_element_element_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsection',
            old_name='event_title',
            new_name='section_title',
        ),
    ]
